name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install Firebase Tools
        run: npm i -g firebase-tools@13.10.2
      - name: Show environment
        run: |
          node -v
          npm -v
          firebase --version
      - name: Write service account key
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          if [ -z "$FIREBASE_SERVICE_ACCOUNT" ]; then echo "FIREBASE_SERVICE_ACCOUNT secret missing" && exit 1; fi
          echo "$FIREBASE_SERVICE_ACCOUNT" > "$RUNNER_TEMP/firebase-sa.json"
          echo "Service account key written to $RUNNER_TEMP/firebase-sa.json"
      - name: Prepare Hosting targets (no-op if exist)
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/firebase-sa.json
        run: |
          firebase target:apply hosting wildcattrio-web-prod wildcattrio-web-prod --project wildcattrio-web-prod || true
          firebase target:apply hosting elevatequotes-web-prod elevatequotes-web-prod --project elevatequotes-web-prod || true
          firebase target:apply hosting calsmartai-web-prod calsmartai-web-prod --project calsmartai-web-prod || true
      - name: Deploy Corporate (wildcattrio-web-prod)
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/firebase-sa.json
        run: firebase deploy --only hosting:wildcattrio-web-prod --project wildcattrio-web-prod --non-interactive --debug
      - name: Deploy Elevate Quotes (elevatequotes-web-prod)
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/firebase-sa.json
        run: firebase deploy --only hosting:elevatequotes-web-prod --project elevatequotes-web-prod --non-interactive --debug
      - name: Deploy CalSmart AI (calsmartai-web-prod)
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/firebase-sa.json
        run: firebase deploy --only hosting:calsmartai-web-prod --project calsmartai-web-prod --non-interactive --debug


